version: 2
registries:
  composer-repository-packages-itineris-co-uk-herokuapp-com:
    type: composer-repository
    url: https://packages-itineris-co-uk.herokuapp.com
    username: dependabot
    password: "${{secrets.COMPOSER_REPOSITORY_PACKAGES_ITINERIS_CO_UK_HEROKUAPP_COM_PASSWORD}}"

updates:
- package-ecosystem: composer
  directory: "/"
  schedule:
    interval: daily
    time: "00:00"
    timezone: Europe/London
  ignore:
  - dependency-name: symfony/mime
    versions:
    - 4.4.19
    - 4.4.20
  - dependency-name: symfony/http-foundation
    versions:
    - 4.4.19
  - dependency-name: symfony/polyfill-intl-normalizer
    versions:
    - 1.22.0
  registries:
  - composer-repository-packages-itineris-co-uk-herokuapp-com
